#!name=🚗 哪吒汽车 [获取签到Token]
#!desc=获取Token用。打开哪吒汽车App。
#!category=tools

[rewrite_local]
^https:\/\/appapi-pki\.chehezhi\.cn:18443\/pivot\/veh-status\/vehicle-status-control\/1\.0\/getAppVehicleData$ url script-request-header https://raw.githubusercontent.com/netcookies/neta-connect/refs/heads/main/scripts/netaConnect.js

[mitm]
hostname = appapi-pki.chehezhi.cn
