events {}

http {
    include       mime.types;
    default_type  text/plain;  # 强制默认类型为 text/plain

    server {
        listen 80 default_server;
        server_name _;

        root /usr/share/nginx/html;

        location / {
            autoindex on;

            # 设置安全响应头
            add_header Cache-Control "max-age=300" always;
            add_header Content-Security-Policy "default-src 'none'; style-src 'unsafe-inline'; sandbox" always;
            add_header Strict-Transport-Security "max-age=31536000" always;
            add_header X-Content-Type-Options "nosniff" always;
            add_header X-Frame-Options "deny" always;
            add_header X-XSS-Protection "1; mode=block" always;
            add_header Access-Control-Allow-Origin "*" always;
            add_header Cross-Origin-Resource-Policy "cross-origin" always;

            # 显式设置 JS 文件的 Content-Type
            types {
                text/plain js;
            }
        }
    }
}

