name: Auto generate changelog

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'ci: Bump Version')"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: BobAnkh/auto-generate-changelog@v1.2.5
        with:
          REPO_NAME: 'netcookies/isulewTools'
          ACCESS_TOKEN: ${{secrets.PAT}}
          REGENERATE_COUNT: -1
          TYPE: 'feat:New Features,fix:Bug Fixes,perf:Performance Improvements,refactor:Refactors,build:Build System,docs:Documentation Changes,chore:Chores,other:Other Changes'
