name: Auto generate changelog

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'ci: Bump Version')"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: BobAnkh/auto-generate-changelog@v1.2.5
        with:
          REPO_NAME: 'netcookies/isulewTools'
          ACCESS_TOKEN: ${{secrets.PAT}}
          REGENERATE_COUNT: -1
          PATH: 'CHANGELOG.md'
          COMMIT_MESSAGE: 'docs(CHANGELOG): update release notes'
          TYPE: 'feat:Feature,fix:Bug Fixes,docs:Documentation,refactor:Refactor,perf:Performance Improvements'
